export * from './interfaces/contacto.model';
export * from './interfaces/educacion.model';
export * from './interfaces/experiencia.model';
export * from './interfaces/habilidad.model';
export * from './interfaces/jwt-dto.model';
export * from './interfaces/login.model';
export * from './interfaces/persona.model';
export * from './interfaces/proyecto.model';
export * from './interfaces/register.model';
